accept http rpc url
kalouo/breadcrumbs pull request #71
Opened 2022-10-25 22:18 UTC by nicolasochem

It is possible to run rewards distributor on the same machine that runs the tezos node.

Or, like in my case, in a k8s service in the same cluster. In this case, http is fine.

2022-10-26 20:23 UTC, cryi requested changes
We technically this is not issue at all to support all protocols. We just have to make sure we forge txs with local forger and whether it goes encrypted or not to RPC does not matter really.

2022-10-26 20:23 UTC, cryi commented on src/config/validate/runtime.ts
> +const validRpcUrl = Joi.string().uri({ scheme: ["https", "http"] });
Technically any protocol is ok if we run in local setup. So we can add tcp here as well.

2022-10-26 20:24 UTC, cryi commented
@kalouo what do you think is best course of action to handle this considering my above comment.

2022-10-29 08:19 UTC, kalouo commented
To be honest I am not sure about the different protocols we want to support. 

We can scope it down to what @nicolasochem needs currently and leave it at that for now.

2022-10-29 08:19 UTC, kalouo approved these changes
LGTM

2022-11-01 11:37 UTC, merged